### ISSUE TITLE
Editable version

### ISSUE THREAD

**Issue by aldredb** [EG-tech/digipres-posters#1]
Hello, can I have an editable version of the images?

**Comment by EG-tech** [comment]
Hello! Unfortunately I originally made these files using Google Drive, so there isn't really a good editable format available (no .odg support in Google Drawings...)

However I have returned to the originals and created and uploaded SVGs, since that was the last format/version available from Drive that I hadn't downloaded - perhaps those will be editable in some software? Best I can do, hope it helps.
